@@startuml test


(*) --> [activate] dispatch

"dispatch" --> [generate] "Palette Store"
"dispatch" --> [generate] "WebView Store" 
"WebView Store" --> Action
"Palette Store"  --> Action
Action --> dispatch

@@enduml

@@startuml Sequence
-> dispatcher : activate
dispatcher -> "Palette Store" : create
"Palette Store" --> dispatcher : dispatch action
@@enduml

@@startuml Activity
(*) --> "create dispatcher"
"create dispatcher" --> "create PaletteStore"
"create PaletteStore" --> "dispatch Action-View"
if "ViewStore which has key of Action exist" then
    -> dispatch the Store
else
    -> create a store 
    -> dispatch the Store

@@enduml

@@startuml usecase
agent dispatcher

node stores{
    [PaletteViewStore]
    [WebViewStore]
}

package Action{
    [searchQuery]
}
node views{
    [Webview]
    [VscodePalette]
}

(start extension) -down-> dispatcher :create
dispatcher -> PaletteViewStore : create
dispatcher -> WebViewStore : create by Action
Action -left-> dispatcher

dispatcher <- stores :regist actions
views -up-> dispatcher : dispatch
stores -down-> views

WebViewStore -> Webview : message
WebViewStore <- Webview : message

User -> Webview : event
@@enduml